project-machine/disko

.github/workflows/build.yml
remove the extra step to cat the coverage file thats generated.
=> simply coverage report generation

util_test.go
Add tests of some of the utils.go helpers.
=> Add tests of findRangeGaps and parseUdevInfo.

lvm.go
Logical Volumes *always* have a volume group.
Physical Volumes are part of zero or one volume group.
It is useful for the struct to contain this information.
=> API: Add VGName to both PV and LV.

disk.go, disk_test.go, disko.go, linux/disk.go, linux/lvm.go, linux/system.go, linux/util.go, linux/util_test.go, linux/virt.go, linux/virt_test.go, util.go, util_test.go
This finishes the implementation of lvm interface by adding
CreateLV, ExtendLV, HasLV, RemoveLV.
Notes:
* HasLV will panic if it's ScanLV fails.
* CreateLV and ExtendLV require size to be unit of extent size.
I'd rather have the operation error than arbitrarily round
up or down.
Also adds Ceiling and Floor functions that can be used in calling CreateLV
and ExtendLV.
createLv("vg0", "lv0", Ceiling(mysize, lvm.ExtentSize) lvm.THICK)
=> Finish Lvm Impl

disk.go, util.go, util_test.go
findRangeGaps assumed sorted input (by start).
This caused a bug when summing available space as walking
the PartitionSet is not guaranteed order.
=> findRangeGaps: fix bug if input was not sorted.

guid.go
Pull request to github.com/rekby/gpt
(https://github.com/rekby/gpt/pull/5) was rejected as unnecessary.
This is just as easy, and drops code.
=> Drop GUIDToString copy, just cast as a gpt.Guid and use String()

linux/disk.go
Partitions not getting correctly specified, for start or end.
which resulted in busted sizes and invalid partitions.
=> Fix conversion of sizes bytes to sectors when creating partitions.

mockos/lvm.go
LV should have the name of vg when it's creating. This  resolves an issue in atom side to maintain the VGs and their corresponding LVs
=> Add name of VG into LV on create

go.mod, go.sum, linux/disk.go, linux/disk_test.go
2 things here:
* Replace newGPTTable with gpt.NewTable from the gpt module.
* Silence a //nolint lint warning.
=> Replace newGPTTable with use of gpt.NewTable, silence a lint warning.

linux/disk.go, linux/disk_test.go, linux/lvm.go, linux/lvm_test.go, linux/lvmdump.go, linux/system.go, linux/util.go, linux/util_test.go, linux/virt.go
There was a build constraint (// +build linux) on the linux package,
but that should not have been needed.
The build constraint meant that you could not run the tests on MacOS.
=> Drop linux build constraint.

disk.go, disk_test.go
Strings are more readable.  This adds support for Unmarshalling as
either a string or an int.  Having strings are nice for just dumping json
as a representation to show things.
When we encode the following disk to json:
disko.Disk{
Name: "sda", Path: "/dev/sda",
Size: 500*1024*1024, SectorSize: 512,
Type: disko.HDD,
Attachment: disko.ATA}
Here is before and after.   Note that attachment and type are now strings rather than ints.  Also, note that we can still un-serialize from integer or string.
--- Before ----         | ---- After -----
{                       | {
"name": "sda",        |   "name": "sda",
"path": "/dev/sda",   |   "path": "/dev/sda",
"size": 524288000,    |   "size": 524288000,
"sectorSize": 512,    |   "sectorsize": 512,
"type": 0,            |   "type": "HDD", …
=> Change AttachmentType and DiskType to marshal to json as string.

demo/main.go, demo/megaraid.go
megaraid disk-summary shows information about virtual disks and disks
that are not in a disk group.
So virtual disks show up like:
$ ./demo megaraid disk-summary
Path     | Name    | Type | State |
/dev/sda | RAID0_2 | SSD  | Optl  |
/dev/sdb | RAID0_3 | HDD  | Optl  |
JBOD or "UBUnsp" (bad) disks show up like:
$ ./demo megaraid disk-summary
Path     | Name      | Type | State  |
| diskid-13 | HDD  | UBUnsp |
/dev/sda | diskid-8  | HDD  | JBOD   |
/dev/sdb | diskid-10 | HDD  | JBOD   |
=> cli: add megaraid disk-summary

go.mod, go.sum, linux/system.go, megaraid/storcli.go
This connects the linux disko.System() interface with a storCli
implementation.  The end result is that now we get improved answers
for the DiskType of a Disk.  If the disk is a virtual megaraid drive
whose DiskGroup is entirely made up of ssd, then you will now see
that its DiskTypetype is SSD.
It is hooked up through go-cache to avoid repeated queries of 'storcli'.
That isn't *slow*, but not fast either.  The assumption is that
those things dont' change very often.  The timeout is set to 5 minutes
here.
=> Connect megaraid to linux System.

disk.go, megaraid/megaraid.go
When dumping json of a DiskSet, I was not getting the custom
MarshalJson on the Disks it contained.  This change seems to
allow to json.MarshalIndent(<diskSet>) and have the strings
output inside, and same for partitions and other things.
=> Change custom MarshalJson to take objects not pointers.

linux/disk.go
Previously getPartitionsBlockDevice("sda") was broken while
getPartitionsBlockDevice("/dev/sda") would work.  This just fixes
the broken case.
Closes #24
=> Fix getPartitionsBlockDevice when provided a name rather than path.

linux/lvm.go
Just a thinko/typo meant that PVs were not getting populated
when scanning VGs.
=> Fix ScanVGs in linux to correctly populate PVs.

demo/megaraid.go, linux/system.go, megaraid/linux.go
Previously Scan would not ever list RAID as the Attachment Type.
This gets that populated for Megaraid disks.
=> Correctly populate RAID into attachment type for MegaRaid disks.

linux/lvm.go
Simple copy-paste error here. RemoveVG should call
lvm vgremove
not
lvm lvremove
=> RemoveVG: fix bug where it attempted to remove an lv, not vg.

linux/lvm.go, linux/lvm_test.go, lvm.go
UUID is helpful in identifying a lvm item, as it is the
guaranteed-unique identifier for a VG, LV, PV.
Add THINPOOL as an LVType.
=> Add lvm UUID to VG, LV, PV.  Add a LVType THINPOOL.

lvm.go, lvm_test.go
Previously, serializing a LVType gave the helpful 0 or 1.
This turns those into more useful values THICK, THIN, THINPOOL.
=> Serialize LVType to strings rather than integers.

linux/disk.go, linux/lvm.go
CreatePV was broken in that it's signature took a name but then passed
that to 'createpv' which requires a path.
It now will take either a path or a name, but still reports to take
just the name for consistency with other things.
=> Fix CreatePV to correctly take kname. Add getKnameAndPathForBlockDevice.

linux/disk.go
fixes the getKnameAndPathForBlockDevice to accept either a path or a
name, find the device name and return the device name and path the way
kernel sees it.
=> make correct kname and path for createPV

megaraid/storcli.go, megaraid/storcli_test.go
2 things:
* Fix storcli disk parsing when a disk is 'Foreign' (F).
* Do not add DriveGroups with ID < 0 to the DriveGroup.
=> Megaraid fix for Foreign disks and small cleanup for DriveGroups.

linux/lvm.go, linux/lvmdump.go
This adds passing arguments to
getPvReport
getLvReport
getVgReport
And then uses those to not get full lvm reports when only one device
is expected.
The big win is that the CreateLV, CreatePV, CreateVG functions
no longer do a scan of all  of lvm after doing their job.  They
specifically ask about the device they know they created.
=> Allow passing arguments to report functions, and use where possible.

linux/lvm.go
CreateVG was not returning error even when it detected one.
=> Return error in CreateVG when command or scan fails.

linux/util.go
This just fixes formatting in cmdError.
It was missing space for indentation and a ':' for error output.
=> Fix formatting in cmdError.

demo/disk.go, disk.go
2 things here:
* Sort output of disk.Details by partition number.  Previously these were just map-ordered (non-ordered)
* Add demo disk show.
=> Add demo 'disk show' command to show human friendly output, sort partition output.

demo/disk.go, demo/main.go, demo/misc.go, linux/disk.go, linux/util.go
Smaller changes here, in general order of notability:
* use addpart instead of 'partx --add' and before doing so,
close the device and settle.  This really should result in
more reliable 'add'.
* deletePartitions - use 'delpart' rather than 'partx --delete'.
also, only call if needed (if the block device does not exist
then do not bother calling delpart)
* 'demo disk show' output more information.
* internal change for formating of an error from a 'runCommand'.
The big thing here is the addition of 'demo misc updown' which just allows tests of create/delete.  An example:
numruns=1 partition=true createpv=true lvm=true
[ #       Start       Last       Size Name            ]
[ 1       3 MiB    253 MiB    250 MiB esp             ]
[ 2     253 MiB   1277 MiB   1024 MiB atx-boot        ]
[ 3 …
=> Add demo 'misc' subcommand and minor changes

disk.go, disk_test.go, linux/disk.go
Now you will get NBD and LOOP show up as attachment types.
This doesn't fit perfectly as an "attachment", but it seems to
fit better than a TYPE.
=> Add knowledge of nbd and loop devices as "attachments".

disk.go, linux/disk.go, linux/disk_test.go
xen blkfront devices are seen in EC2 instances.
The change here identifies them by their syspath.
=> Identify xen blkfront devices as new attachment type XENBUS.

disk.go, disk_test.go, linux/system.go, linux/system_test.go
Cloud systems often have 'ephemeral' devices, which are backed by disks
in the local system.  These are generally faster or cheaper but less
reliable than other disks.
This adds a Disks.Properties{} that has a list of properties.
The only property at this point is Ephemeral.
=> Add properties to a disk to identify 'Ephemeral'.

demo/megaraid.go
The 'name' field of a virtual drive may be empty.  If that is the
case, show 'virtid-<num>' in output of 'megaraid disk-summary'.
Before:
$ ./demo megaraid disk-summary
Path     | Name | Type | State |
/dev/sda |      | HDD  | Optl  |
After:
$ ./demo megaraid disk-summary
Path     | Name     | Type | State |
/dev/sda | virtid-0 | HDD  | Optl  |
=> Show virt-id in demo output if 'name' is empty.

linux/disk.go, linux/virt_test.go
- use fmt.Sprint() rather than conversion of a fix bad use of string() 
to convert an int (iota) to a string in a test case Errorf.
- Simplify the check for identifing virtio ssds via hack of serial name.
=> 2 small changes

linux/lvm.go
The default metadata size (vg_mda_size) is 4MiB.
We have had experience where this is limiting.  So just bump
the size to 128MiB.
=> Create VGs with metadata size of 128MiB.

.golangci.yml, demo/misc.go, disk_test.go, linux/disk.go, linux/disk_test.go, linux/lvm.go, linux/root_helpers_test.go, linux/root_test.go, linux/util_test.go, megaraid/storcli.go, megaraid/storcli_test.go, mockos/lvm_test.go, mockos/system_test.go, partid/partid.go, ptimg/main.go
Disable the gomnd (magic number) linter on test files.
Adjust code to use consts in most cases where we were ignoring
the linter (// nolint:gomnd).
=> Adjust code for less ignoring gomnd.

.github/workflows/build.yml, linux/lvm.go, linux/root_test.go
A few quirks that allow us to keep the same old CreateLV interface:
* The caller of CreateLV has to know that when creating a THIN lv, they
have to pass the VG name as <vgname>/<thinpoolName>.
* For THINPOOL types, the name given is the name of the thin pool.
We accept the defaults from lvm for tdata and tmeta pool names.
(creation of MyThinPool will have hidden volumes created named
mythinpool_tdata and mythinpool_tmeta).
* The MetaData pool size (--poolmetadatasize=) is hard coded to
1GiB and a spare pool is created (--poolmetadataspare=y).
=> Add support for CreateLV with thin or thinpool.

linux/root_test.go, linux/system.go, linux/system_test.go, mockos/system.go, mockos/system_test.go, system.go
When first partitioning a disk, the caller is likely to want to
create more than one partition.  The addition of CreatePartitions
means that the caller does not have to loop over CreatePartition
in order to do so.
This reduces the calls to open(disk), flock(disk), and Settle.
=> Add System.CreatePartitions to add multiple partitions at once.

linux/disk.go
for mmcblk disk like Raspberry Pi can use.
root@ubuntu:/tmp# ls -l /sys/block/|grep mm
lrwxrwxrwx 1 root root 0 Mar  3 13:56 mmcblk0 -> ../devices/platform/soc/3f202000.mmc/mmc_host/mmc0/mmc0:59b4/block/mmcblk0
=> modify: for mmcblk disk like Raspberry Pi

linux/system.go, megaraid/linux.go, megaraid/megaraid.go, megaraid/storcli.go, megaraid/storcli_test.go
For megaraid cards that do not support raid (true story), the
/c0/dall request will return Un-supported.  But you can still get the
same information from the 'storcli /c0 show'.
Fixes #98.
=> For megaraid parsing, use /c0 show instead of /c0/dall show.

linux/disk.go
The logic here was just wrong. It was attempting to avoid a
request to zeroStartEnd to write past the end of the disk, but
actually meant that it would always use the disk end.
=> Fix error in wipeDisk preventing the wiping of partition ends.

linux/lvm.go
lvcreate defaults to not zeroing devices if called the way we
are calling it (--yes --activate=y --setactivationskip=n).
That seems very odd.
Without zero'ing, it seems that eventually the user *will* create
a volume that has data on it that is problematic.
=> Zero logical volumes during lvcreate.

linux/disk.go, linux/disk_test.go, linux/root_test.go
If the user called CreatePartition with a partition that had an
empty ID, then it would be created with an empty id.
That is almost certainly not the desired behavior. In that case,
generate an ID.
=> Do not allow creation of a GPT partition without a guid.

.github/workflows/lint.yml, .golangci.yml, Makefile, disk.go, linux/disk.go, linux/disk_test.go, linux/lvm.go, linux/lvmdump.go, linux/lvmdump_test.go, linux/root_helpers_test.go, linux/root_test.go, linux/system.go, linux/system_test.go, linux/util_test.go, linux/virt.go, megaraid/storcli.go, ptimg/main.go
This takes over the good work in @raharper 's https://github.com/anuvu/disko/pull/107 pull request.
I just added to it with some a 'make lint' target that downloads and uses the correct version of golint, so now a developer can easily just run 'make lint' and use the version that c-i will use.
=> golint cleanups and adjustments.

disk.go, linux/disk.go, linux/disk_test.go, linux/root_test.go, linux/system.go, mockos/system.go, system.go
This allows caller to update the Name, ID, and GUID on a partition type.
Previously to accomplish this, caller would have to delete the partition
and add a new one with the updated info.
For now, the size of the partition is not updated.
=> Add UpdatePartition and UpdatePartitions interface.

Makefile, linux/lvm.go
Wipe luks2 headers after lvcreate.
Versions of libblkid, before 2.33 would not completely wipe luks 2
headers.  After we create a thick LV, wipe any remaining headers
ourselves.
This should not be that big of a problem, but when it was mixed with
a liberal running of 'cryptsetup luksUUID' after LV creation things
went awry.  cryptsetup will automatically repair a broken header
that it finds, and it would find such a header because lvm did not
completely wipe it.  To be clear, 'cryptsetup luksUUID' is not
a read-only operation.
Also complicating things was the fact that we were creating luks 2
volumes and then running with an old LVM.
2 other changes snuck in here:
* Update to newer lint.  v1.47.2 to support golang 1.18
* Fix a Makefile error resulting in 'bad substitution'
=> Wipe luks2 headers after lvcreate

linux/lvm.go
Previously we were formating luks devices without a '--type='.
That left it up to the system default to be either luks1 or luks2.
Recent OS would be luks2, but older ones (centos 7) would be luks1.
We should be explicit.
=> Explicitly format luks devices with luks2.

linux/disk.go, linux/disk_test.go
Change zeroStartEnd to zero 8 more bytes,
* 4 bytes at offset 1mib (VMFS)
* 4 bytes at offset 2mib (VMFS_volume_member)
Fixes #121.
=> Wipe VMFS filesystem signatures

linux/disk.go
Fix the thinko which returns nil when addPartitioSetGPT fails by returning the err instead of nil.
=> fix: return err when addPartitionSetGPT fails

linux/util.go, linux/util_test.go
The current parser returns an error when it encounters newer prefix values in the output of udevadm info.  Anytime a system upgrades to a newer release, there is a change new fields will be present preventing disko from producing any output.
- Update and document prefixes defined in systemd v255
- Replace error with an warning output
=> linux/udev: fix udevadm info parser to not be fatal

linux/disk_test.go, linux/system.go
The raid controller merge regressed the path for non-raid attached disks
and all such disks were classified as HDDs.  This was found under KVM
testing where disko uses a prefix in the ID_SERIAL property to set the
disk type to SSD.
- Add coverage for this path
=> Fix regression where non-raid attached disks did not determine correct disk type

mpi3mr/storcli2.go, mpi3mr/storcli2_test.go
When querying state from the controller with drives that have existing RAID config, the PhysicalDrive.DG field has the letter 'F' specified. Handle this case by assigning another negative number (-2).  Also Allocate a new DGUnknown value (-99) and use this when we encounter another string value that we don't know about rather than crashing.
Add a test case for this scenario.
Additional changes
- Dropped commented out tests
- Created const values for the DG properties
=> fix: Handle Drives with existing config from another RAID adapter
