.github/codecov-upstream.yml
.github/workflows/build.yml
doc.go

doc change for PR test

---

util_test.go

Previous commit had golint complaints in it.
Just fix those.

Fix golint complaints.

---

linux/lvm.go
lvm.go
mockos/lvm.go

fix LV api to carry vg name

---

mockos/lvm.go
mockos/lvm_test.go

add lv and crypt test cases

---

.golangci.yml
linux/disk.go
linux/disk_test.go
linux/lvm.go
linux/lvm_test.go
linux/lvmdump.go
linux/lvmdump_test.go
linux/system.go
linux/util.go
linux/util_test.go
system.go

Not everything here, but more than was.

Some linux lvm Implementation

---

disk.go
disk_test.go
lvm.go
lvm_test.go

Just make it so printing of these types does something sane.

Add String functions for AttachmentType and DiskType, LVType.

---

disk.go
disk_test.go
linux/disk.go
mockos/lvm_test.go
mockos/system_test.go
util.go

The use of 'End' can be confusing.  If a partition has
Start: 512
End: 1023
It is not obvious whether or not the Partition includes byte 1023.
It is more obvious if we use 'Last'.

Change 'End' to 'Last' in Partition, and clarify bytes in doc.

---

go.mod
go.sum
linux/disk.go
linux/disk_test.go
linux/system.go

This should allow CreatePartition to be used, and with the added unit
test it is at least somewhat tested.

Add implementation for linux CreatePartition

---

linux/disk.go

fix minor errors in disk type detection

---

megaraid/megaraid.go
megaraid/storcli.go
megaraid/storcli_test.go

This adds a megaraid package that uses storecli to query adapters.
It can be used like this:
mraid := megaraid.StorCli()
ctrl, _ := mraid.Query(0)
jbytes, _ := json.MarshalIndent(&ctrl, "", "  ")
fmt.Printf("%s\n", string(jbytes))
Here is an example of the content: [dump.json.txt](https://github.com/anuvu/disko/files/4247096/dump.json.txt)

Add Megaraid package.

---

demo/disk.go
demo/main.go
demo/megaraid.go
go.mod
go.sum

This just adds a "demo" (disco demolition) command.
It is really only for demo (demonstration) at this point.

Add the demo cli

---

linux/lvm.go
lvm.go
mockos/lvm.go
mockos/lvm_test.go

Allow the re-naming of an LV.
Closes #34

Add VolumeManager.RenameLV.

---

linux/disk.go
linux/lvm.go
linux/system.go

3 commits here related to wiping.
a.) Explicitly zero lvm objects when created or initialized.
b.) Zero start and end of a to-be-created partition addPartitionSet.
c.) Implement linux system Wipe.

Wipe Please

---

demo/disk.go

This is just a simple tool to dump the information on a disk that Disko
is working with.

Add demo 'disk scan' which does a scan of disks and json dumps the output.

---

demo/lvm.go
demo/main.go

dump-vgs will do a scan and dump the data that disko read.

Add lvm subcommand and dump-vgs.

---

linux/lvm.go

Read `dmsetup table` output to populate path and name to the decrypted
device for a logical volume.
Fixes #47.

Populate LV.DecryptedLVName and DecryptedLVPath.

---

linux/lvm.go

We saw an error in actual use where 'dmsetup table --concise' returned
a record with 4 fields.  The error reported was:
unexpected data in dmsetup table --concise. Found 4 fields, expected 5:
docker-252:67-393218-467<cut>bdbdb,,110,rw

In getLuksInfo allow for records with 4 fields.

---

linux/disk.go
linux/disk_test.go
linux/util_test.go

2 things:
* Add range checking in addPartitionSet.
* tests: clean up a temp file that was being left.

Add range checking in addPartitionSet and clean up a test tempfile.

---

linux/lvm.go

Instead of making calls to ScanPVs and ScanLVs when walking the
response from ScanVGs, we only do those once.
The ScanPV call is very slow if there are a lot of block devices
(including lvm block devices).
Overall, this results in considerable speedup.
|  vm  | hardware
with-change | 1.22 | 1.35
without     | 1.74 | 2.99
They're by no means scientific numbers, but it is a considerable win.

Speed up ScanVGs by only scanning PVs and LVs at most once.

---

linux/disk.go

If a disk is mounted, then adding a partition will not result in udev
correctly signalling the kernel to reread the partition table.
This is because udev events just call 'blkrereadpt' (reread the whole
partition table).
We use 'partx' here, but we could just as well use 'addpart' and
'delpart'.  Even better would be to call the ioctl directly.
Fixes #53.

Call partx --add and --delete after adding or removing partitions.

---

demo/misc.go

This adds creation of luks devices (on lvm logical volumes) to the
updown code.  It will do luks by default now, skipping if --skip-luks
is provided.
$ ./demo misc updown --skip-luks --loops=30 /dev/sdf
...
[0] created luks device myvg0_mylv0_crypt

Add luks to demo updown.

---

linux/disk.go

Previously there was a bug where calling newProtectiveMBR would fail
if data in the partition table had invalid values in the bootable flag.
What we do here is just set the bytes of the partition table to a fully
zeroed MBR before then creating the partitions correctly.
There is not a method exposed in MBR library to set the bootable flag,
so we just zero the whole area (NonBootable is represented by 0x00
so this is fine).

Zero the partition table before writing a protective MBR.

---

linux/disk.go

Both the GPT table and ProtectiveMBR need to be updated or
re-written if the disk size changes.  That is not a very common
event with real disks (disks don't magically get more bytes).
But, it is common for virtual disks to be "grown" (zeros added
to the end).
The GPT header at the beginning of a disk contains a reference
to the location of a copy (HeaderCopyStartLBA) which is typically
at the end of the disk.  The ProtectiveMBR is supposed to span
the entire disk.  So both of these things have to be updated
if the disk changes size.
The change here is just to make sure we update both whenever
we write a GPT partition table.
A simple 'diff' doesn't show it well, but what happened is:
a.) move writeProtectiveMBR from writeNewGPTTable to writeGPTTable
b.) pass a disk size into writeGPTTable …

Always update Protective MBR and Secondary GPT Table when writing GPT.

---

Makefile

Now you should be able to just type 'make' and have it build and test.
Probably more complicated the necessary.

Add Makefile for simple build.

---

ptimg/main.go

Tycho had seen this and mentioned in review, but it got merged
before it got addressed.

Drop commented out code from ptimg/main.go.

---

demo/misc.go
linux/lvm.go

Previously ExtendLV(vg, lv) would not extend the luks device.
Now call 'cryptsetup resize' to update the luks device after
extending the LV.
Also update the demo program to extend an LV.  I'm testing this
on a loop device with:
i=/tmp/my.img;
rm -f $i;
truncate --size=2G $i;
lodev=$(losetup --find --show $i);
udevadm settle;
echo $lodev;
./demo misc updown $lodev;
udevadm settle;
cryptsetup close myvg0_mylv0_crypt;
udevadm settle;
vgremove myvg0 --force;
for p in ${lodev}p*; do [ -b "$p" ] || continue;
(set -x; delpart $lodev ${p##*p} ); done;
losetup --detach=$lodev

Make ExtendLV call 'cryptsetup resize' if luks device is open.

---

.github/workflows/build.yml
Makefile
linux/root_helpers_test.go
linux/root_test.go

Add integration tests that can be run with:
make test-all
or
go test --tags=integration

Linux Integration Tests

---

demo/disk.go
linux/disk.go
linux/disk_test.go
linux/system.go

Previously, system.Wipe() would only wipe the first and last MiB
of the disk.  Now, it will also wipe the first and last MiB of
any partitions on the disk.
Also, add 'demo disk wipe' subcommand that calls this.

Make Wipe() wipe partitions, Add demo disk wipe.

---

linux/root_helpers_test.go
linux/root_test.go

This isn't specifically disko codepath (disko doesn't currently
deal with filesystems), but it is codepath that the caller will
use, so lets verify it works.

Add test using resize2fs after extend.

---

.github/workflows/build.yml
Makefile

Split different sections means you can get more fine-grained output.

Split up workflow and tests a bit, so times in c-i mean more.

---

partid/partid.go

EBD0A0A2-B9E5-4433-87C0-68B6B72699C7 is Microsoft Basic Data.
https://en.wikipedia.org/wiki/Microsoft_basic_data_partition

Add knowledge of GPT guid for Microsoft Basic Data.
